spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management: # spring-boot-actuator 설정
  endpoint:
    web:
      exposure:
        include: health # health endpoint 추가
    health:
      show-details: always # health 자세한 정보 추가
springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: ASC
    operationsSorter: controller
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**
    - /