server:
  port: ${SERVER_PORT}

spring:
  datasource: # 데이터베이스 연결 관련
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    # 데이터베이스 접속 url
    # host == 아이피
    # db_databasename == 데이터베이스 이름
    username: ${DATABASE_USERNAME} # 데이터베이스 사용자 id
    password: ${DATABASE_PASSWORD} # 데이터베이스 사용자 비번
