spring:
  datasource: # 데이터베이스 연결 관련
    url: jdbc:mysql://localhost:${DATABASE_LOCAL_PORT}/${DATABASE_NAME}
    # 데이터베이스 접속 url
    # host == 아이피
    # db_databasename == 데이터베이스 이름
    username: root # 데이터베이스 사용자 id
    password: ${DATABASE_LOCAL_PASSWORD} # 데이터베이스 사용자 비번