server:
  port: ${SERVER_PORT}

spring:
  datasource: # 데이터베이스 연결 관련
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&characterEncoding=utf8
    # 데이터베이스 접속 url
    # host == 아이피
    # db_databasename == 데이터베이스 이름
    username: ${DATABASE_USERNAME} # 데이터베이스 사용자 id
    password: ${DATABASE_PASSWORD} # 데이터베이스 사용자 비번
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${EMAIL_USERNAME} # SMTP 계정 아이디
    password: ${EMAIL_PASSWORD} # SMTP 계정 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0