spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource: # 데이터베이스 연결 관련
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    # 데이터베이스 접속 url
    # host == 아이피
    # db_databasename == 데이터베이스 이름
    username: ${DATABASE_USERNAME} # 데이터베이스 사용자 id
    password: ${DATABASE_PASSWORD} # 데이터베이스 사용자 비번
    driver-class-name: com.mysql.cj.jdbc.Driver # 드라이버 이름

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # mysql 버전을 따라가는 Hibernate 구현체 문법 설정
    hibernate:
      ddl-auto: validate
    show-sql: true
management: # spring-boot-actuator 설정
  endpoint:
    web:
      exposure:
        include: health # health endpoint 추가
    health:
      show-details: always # health 자세한 정보 추가

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: ASC
    operationsSorter: controller
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

extends:
  app-id: ${KAKAO_DEVELOPERS_APP_ID}
  jwt-secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AMAZON_ACCESS_KEY}
      secret-key: ${AMAZON_SECRET_KEY}
    s3:
      bucket: ${AMAZON_S3_BUCKET}
    region:
      static: ${AMAZON_REGION}
    stack:
      auto: false