name: Java CD with ssh

on:
    push:
        branches: ["develop"]

permissions:
    contents: read

jobs:
    ssh:
        runs-on: ubuntu-latest

        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /root/github/api-server
                      git pull origin develop
                      chmod +x ./gradlew
                      ./gradlew clean && ./gradlew build
                      bash /root/app/kill.sh
                      bash /root/app/run.sh
